services:
  haproxy:
    image: haproxy:2.9
    container_name: lora-haproxy
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '80:80'
    depends_on:
      - nodered
      - grafana
      - influxdb
    networks:
      - lora_stack_net


  nodered:
    build:
      context: ./docker/nodered
    image: lora-nodered:latest
    container_name: lora-nodered
    environment:
      - TZ=UTC
      - NODE_RED_USERNAME=admin
      - NODE_RED_PASSWORD=${NODE_RED_PASSWORD}
      - FLOWS=flows.json
    volumes:
      - nodered_data:/data
    networks:
      - lora_stack_net

  influxdb:
    image: influxdb:3-core
    container_name: lora-influxdb
    environment:
      - INFLUXD_HTTP_BIND_ADDRESS=:8181
      - INFLUXD_HIDE_LEGACY_NOTICE=true
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=lora-org
      - INFLUX_BUCKET=lora-bucket
      - INFLUX_USER=influx_admin
      - INFLUX_USER_PASSWORD=${INFLUX_PASSWORD}
      - INFLUXD_NODE_ID=${INFLUXD_NODE_ID}
      - INFLUXD_LOG_FILTER=${INFLUXD_LOG_FILTER}
      - INFLUXD_DATA_DIR=${INFLUXD_DATA_DIR}
    command: >
      bash -c "set -e;
        exec influxdb3 serve --node-id ${INFLUXD_NODE_ID} --object-store file --data-dir ${INFLUXD_DATA_DIR} --log-filter ${INFLUXD_LOG_FILTER}"
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - lora_stack_net
    user: root

  grafana:
    image: grafana/grafana:latest
    container_name: lora-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - lora_stack_net

  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: lora-mosquitto
    environment:
      - TZ=UTC
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    ports:
      - '1883:1883'
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    command: >
      sh -c "set -eu;
        USERNAME=$${MOSQUITTO_USERNAME:-mqtt};
        PASSWORD=$${MOSQUITTO_PASSWORD:-ChangeMeMQTT123!};
        PASSWORD_FILE=/mosquitto/config/password;
        if [ -f \"$${PASSWORD_FILE}\" ]; then
          mosquitto_passwd -b \"$${PASSWORD_FILE}\" \"$${USERNAME}\" \"$${PASSWORD}\";
        else
          mosquitto_passwd -b -c \"$${PASSWORD_FILE}\" \"$${USERNAME}\" \"$${PASSWORD}\";
        fi;
        exec mosquitto -c /mosquitto/config/mosquitto.conf"
    networks:
      - lora_stack_net

volumes:
  nodered_data:
  influxdb_data:
  grafana_data:
  mosquitto_data:
  mosquitto_log:

networks:
  lora_stack_net:
    driver: bridge
